# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6fdf1e580e87984a6b6c5a786a0c375bb026281c23c098c0f4fda82cec46cf4f1cc20088c84f55357824d827743e5175757a25585ca26536336805d14485edd3

test:
  secret_key_base: 96a35aad34c476602ff8944a2e07d4a3280653df00357f543cc388a8275ea7eab220fd20356083e00ef12cc162aa1e0470e6999352fd73ed1e4fada1668d4372

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
